In [187]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [188]:
df = pd.read_csv('C:/Users/LEXEFF/Desktop/Python/carsClean1.csv')

In [189]:
df

year  selling_price  km_driven    fuel seller_type  transmission  owner  \
0     2014         450000     145500  Diesel  Individual             1    1.0   
1     2014         370000     120000  Diesel  Individual             1    2.0   
2     2010         225000     127000  Diesel  Individual             1    1.0   
3     2007         130000     120000  Petrol  Individual             1    1.0   
4     2017         440000      45000  Petrol  Individual             1    1.0   
...    ...            ...        ...     ...         ...           ...    ...   
6791  2013         320000     110000  Petrol  Individual             1    1.0   
6792  2007         135000     119000  Diesel  Individual             1    4.0   
6793  2009         382000     120000  Diesel  Individual             1    1.0   
6794  2013         290000      25000  Diesel  Individual             1    1.0   
6795  2013         290000      25000  Diesel  Individual             1    1.0   

      max_power  seats  
0         74.00    5.0  
1        103.52    5.0  
2         90.00    5.0  
3         88.20    5.0  
4         81.86    5.0  
...         ...    ...  
6791      82.85    5.0  
6792     110.00    5.0  
6793      73.90    5.0  
6794      70.00    5.0  
6795      70.00    5.0  

[6796 rows x 9 columns]

In [190]:
df[df['selling_price'] ==10000000]

year  selling_price  km_driven    fuel seller_type  transmission  owner  \
145  2017       10000000      30000  Petrol  Individual             2    1.0   

     max_power  seats  
145      400.0    4.0

In [191]:
#df=df.drop(labels = [145],axis = 0)

In [192]:
from sklearn.preprocessing import MinMaxScaler


In [193]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical = ['fuel', 'seller_type']
numeric_features = [col for col in df.columns if col not in categorical]

column_transformer = ColumnTransformer([
    ('ohe', OneHotEncoder(drop='first'), categorical),
    ('scaling', MinMaxScaler(), numeric_features)
])

df_transformed = column_transformer.fit_transform(df)


In [194]:
df_transformed

array([[1.        , 0.        , 0.        , ..., 0.        , 0.11220044,
        0.25      ],
       [1.        , 0.        , 0.        , ..., 0.25      , 0.19259259,
        0.25      ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.15577342,
        0.25      ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.1119281 ,
        0.25      ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.10130719,
        0.25      ],
       [1.        , 0.        , 0.        , ..., 0.        , 0.10130719,
        0.25      ]])

In [195]:
lst = list(column_transformer.transformers_[0][1].get_feature_names())
lst.extend(numeric_features)

df_transformed = pd.DataFrame(df_transformed, columns=lst)

df_transformed.head()

x0_Diesel  x0_LPG  x0_Petrol  x1_Individual  x1_Trustmark Dealer      year  \
0        1.0     0.0        0.0            1.0                  0.0  0.769231   
1        1.0     0.0        0.0            1.0                  0.0  0.769231   
2        1.0     0.0        0.0            1.0                  0.0  0.615385   
3        0.0     0.0        1.0            1.0                  0.0  0.500000   
4        0.0     0.0        1.0            1.0                  0.0  0.884615   

   selling_price  km_driven  transmission  owner  max_power  seats  
0       0.042126   0.061640           0.0   0.00   0.112200   0.25  
1       0.034102   0.050837           0.0   0.25   0.192593   0.25  
2       0.019559   0.053803           0.0   0.00   0.155773   0.25  
3       0.010030   0.050837           0.0   0.00   0.150871   0.25  
4       0.041123   0.019064           0.0   0.00   0.133606   0.25

In [196]:
X = df_transformed.drop(['selling_price'], axis=1)

y = df_transformed['selling_price']

In [197]:
df_transformed['selling_price']

0       0.042126
1       0.034102
2       0.019559
3       0.010030
4       0.041123
          ...   
6791    0.029087
6792    0.010532
6793    0.035306
6794    0.026078
6795    0.026078
Name: selling_price, Length: 6796, dtype: float64

In [198]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

X_train.shape, X_test.shape

((5097, 11), (1699, 11))

In [199]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

pred = model.predict(X_test)

In [200]:
print(y_test)

5603    0.011033
852     0.039619
2182    0.317954
5820    0.071214
5648    0.006018
          ...   
4928    0.059178
292     0.030592
1142    0.037111
4305    0.072217
4610    0.117352
Name: selling_price, Length: 1699, dtype: float64


In [201]:
print(pred)

[0.03107745 0.03345843 0.25688617 ... 0.05205389 0.02825188 0.20473177]


In [202]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
mean_absolute_error(y_test, pred), mean_squared_error(y_test, pred)

(0.027344943755379623, 0.0020274886993484364)

In [203]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
mean_absolute_error(y_test, pred), mean_squared_error(y_test, pred)

(0.027344943755379623, 0.0020274886993484364)

In [204]:
y=df['selling_price']

In [205]:
y

0       450000
1       370000
2       225000
3       130000
4       440000
         ...  
6791    320000
6792    135000
6793    382000
6794    290000
6795    290000
Name: selling_price, Length: 6796, dtype: int64

In [206]:
MIN = y.min()
MAX=y.max()

In [207]:
y_test_vosst = [z_tr*(MAX-MIN)+MIN for z_tr in y_test]


In [208]:
y_test_vosst

[140000.0,
 425000.00000000006,
 3200000.0,
 740000.0,
 90000.0,
 700000.0,
 220000.0,
 200000.0,
 340000.0,
 645000.0,
 780000.0,
 3974999.9999999995,
 550000.0,
 750000.0,
 2625000.0,
 170000.0,
 509999.0,
 2825000.0,
 793000.0000000001,
 650000.0,
 310000.0,
 180000.0,
 250000.0,
 630000.0000000001,
 580000.0,
 210000.0,
 2500000.0,
 475000.0,
 700000.0,
 204999.0,
 425000.00000000006,
 1075000.0,
 180000.0,
 350000.0,
 455000.00000000006,
 525000.0,
 750000.0,
 650000.0,
 764000.0,
 365000.0,
 2450000.0,
 450000.0,
 700000.0,
 600000.0,
 310000.0,
 300000.0,
 150000.0,
 1325000.0,
 400000.00000000006,
 550000.0,
 470000.0,
 380000.00000000006,
 320000.0,
 600000.0,
 380000.00000000006,
 500000.00000000006,
 750000.0,
 550000.0,
 1575000.0,
 975000.0,
 600000.0,
 275000.0,
 170000.0,
 5500000.0,
 400000.00000000006,
 819999.0,
 200000.0,
 1520000.0000000002,
 220000.0,
 500000.00000000006,
 500000.00000000006,
 290000.0,
 350000.0,
 1689999.0,
 550000.0,
 290000.0,
 411000.000000000

In [209]:
pred_vosst =  [z_p*(MAX-MIN)+MIN for z_p in pred]

In [210]:
pred_vosst

[339841.25420721574,
 363579.5628277298,
 2591154.383689233,
 831357.6253739757,
 -129736.81351039873,
 598296.6272662274,
 210090.11458719286,
 56903.21908329509,
 481669.5266819235,
 1523895.8665452215,
 658149.9430560494,
 2789323.459588728,
 1042970.0240275202,
 366702.2321142235,
 2621339.0944980932,
 142487.64863930029,
 394136.36264972953,
 2574966.2582998667,
 904721.0902790247,
 354694.6350233287,
 346596.01907999255,
 -58218.48021953147,
 147496.91157340712,
 724893.5696473954,
 597018.269694019,
 95934.65453032836,
 2267826.349291543,
 94250.28354822544,
 693995.5147123308,
 196057.89346800756,
 772415.1785452325,
 2520174.5109512797,
 137621.15927324613,
 48494.36607412508,
 506731.8203774135,
 861554.2761278803,
 509112.6630554162,
 535395.097763743,
 725647.3272848988,
 1081351.368479064,
 2290727.8505908526,
 453176.6156423511,
 1147393.4867414702,
 1268229.6696816608,
 404771.00660234626,
 554321.8360127268,
 -412819.48929500935,
 932790.0468691153,
 439635.1630622803,


In [211]:
mean_absolute_error(y_test_vosst, pred_vosst), mean_squared_error(y_test_vosst, pred_vosst)

(272629.11658607854, 201534241883.19073)

In [212]:
model.coef_

array([-0.00556986,  0.00857271, -0.01342434, -0.02669725, -0.03722565,
        0.1068131 , -0.1985113 ,  0.04388297,  0.00446207,  0.48931857,
       -0.04625823])

In [213]:
X

x0_Diesel  x0_LPG  x0_Petrol  x1_Individual  x1_Trustmark Dealer  \
0           1.0     0.0        0.0            1.0                  0.0   
1           1.0     0.0        0.0            1.0                  0.0   
2           1.0     0.0        0.0            1.0                  0.0   
3           0.0     0.0        1.0            1.0                  0.0   
4           0.0     0.0        1.0            1.0                  0.0   
...         ...     ...        ...            ...                  ...   
6791        0.0     0.0        1.0            1.0                  0.0   
6792        1.0     0.0        0.0            1.0                  0.0   
6793        1.0     0.0        0.0            1.0                  0.0   
6794        1.0     0.0        0.0            1.0                  0.0   
6795        1.0     0.0        0.0            1.0                  0.0   

          year  km_driven  transmission  owner  max_power  seats  
0     0.769231   0.061640           0.0   0.00   0.112200   0.25  
1     0.769231   0.050837           0.0   0.25   0.192593   0.25  
2     0.615385   0.053803           0.0   0.00   0.155773   0.25  
3     0.500000   0.050837           0.0   0.00   0.150871   0.25  
4     0.884615   0.019064           0.0   0.00   0.133606   0.25  
...        ...        ...           ...    ...        ...    ...  
6791  0.730769   0.046601           0.0   0.00   0.136302   0.25  
6792  0.500000   0.050414           0.0   0.75   0.210240   0.25  
6793  0.576923   0.050837           0.0   0.00   0.111928   0.25  
6794  0.730769   0.010591           0.0   0.00   0.101307   0.25  
6795  0.730769   0.010591           0.0   0.00   0.101307   0.25  

[6796 rows x 11 columns]

In [183]:
n=0
for x in X.columns:
    print(x,'=',model.coef_[n])
    n+=1

x0_Diesel = -0.00556986480420493
x0_LPG = 0.008572709780918245
x0_Petrol = -0.013424337939190366
x1_Individual = -0.02669725030470101
x1_Trustmark Dealer = -0.03722564617331346
year = 0.10681309987395733
km_driven = -0.19851129664167944
transmission = 0.04388297132226735
owner = 0.004462067578474502
max_power = 0.48931857340761414
seats = -0.046258228463429474


In [215]:
importances = pd.DataFrame({'weights': model.coef_, 'features': X_train.columns}).sort_values(by='weights')
importances

weights             features
6  -0.198511            km_driven
10 -0.046258                seats
4  -0.037226  x1_Trustmark Dealer
3  -0.026697        x1_Individual
2  -0.013424            x0_Petrol
0  -0.005570            x0_Diesel
8   0.004462                owner
1   0.008573               x0_LPG
7   0.043883         transmission
5   0.106813                 year
9   0.489319            max_power

In [216]:
import pickle

with open('CarPriceModel.pickle', 'wb') as f:
    pickle.dump(model, f)

In [217]:
with open('CarPriceModel.pickle', 'rb') as f:
    model = pickle.load(f)